OC.L10N.register(
    "text2image_stablediffusion",
    {
    "Local Image Generation with Stable Diffusion" : "Локальная генерация изображения со Stable Diffusion",
    "Image generation using Stable Diffusion by Stability AI running locally" : "Генерация изображений с использованием Stable Diffusion от Stability AI, запускаемая локально",
    "Image generation provider using Stable Diffusion by Stability AI\n\nThe models run completely on your machine. No private data leaves your servers.\n\nAfter installing this app you will need to run\n\n    occ text2image_stablediffusion:download-model\n\n## Ethical AI Rating\n### Rating: 🟢\n\nPositive:\n* the software for training and inference of this model is open source\n* the trained model is freely available, and thus can be ran on-premises\n* the training data is freely available, making it possible to check or correct for bias or optimise the performance and CO2 usage.\n\nLearn more about the Nextcloud Ethical AI Rating [in our blog](https://nextcloud.com/blog/nextcloud-ethical-ai-rating/)." : "Поставщик генерации изображений с использованием Stability Diffusion от Stability AI\n\nМодели полностью работают на вашем устройстве. Никакие личные данные не покидают ваши серверы.\n\nПосле установки этого приложения вам нужно будет запустить\n\nocc text2image_stablediffusion:download-model\n\n## Этический рейтинг ИИ\n### Рейтинг: 🟢\n\nПоложительное:\n* программное обеспечение для обучения и вывода этой модели имеет открытый исходный код\n* обученная модель находится в свободном доступе, поэтому ее можно запускать локально\n* данные тренировок находятся в свободном доступе, что позволяет проверить или исправить погрешности или оптимизировать производительность и использование CO2.\n\nУзнайте больше о этическом рейтинге ИИ Nextcloud [в нашем блоге](https://nextcloud.com/blog/nextcloud-ethical-ai-rating/).",
    "Status" : "Состояние",
    "Background Jobs are not executed via cron. This app requires background jobs to be executed via cron." : "Фоновые задания не выполняются через cron. Это приложение требует выполнения фоновых заданий через cron.",
    "Resources" : "Ресурсы",
    "Node.js" : "Node.js",
    "Checking Node.js" : "Выполняется проверка Node.js",
    "Could not execute the Node.js binary. You may need to set the path to a working binary manually." : "Не удалось запустить выполнение двоичного файла Node.js. Попробуйте указать путь до бинарного файла вручную.",
    "Node.js {version} binary was installed successfully." : "Двоичный файл библиотеки Node.js {version} успешно установлен.",
    "Failed to load settings" : "Не удалось загрузить параметры",
    "Failed to save settings" : "Не удалось сохранить параметры"
},
"nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || (n%10>=5 && n%10<=9) || (n%100>=11 && n%100<=14)? 2 : 3);");
